{{ if .Values.global.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-green
  labels:
    app: voting-app
    tier: vote
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      tier: vote
  template:
    metadata:
      labels:
        tier: vote
        slot: green
    {{- include "PodTemplate" .Values | indent 4}}
{{end}}

