apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-app
    tier: vote
  name: vote-service
spec:
  {{- include "ServiceTemplate" .Values | indent 2}}
  selector:
    tier: vote
    slot: {{.Values.global.productionSlot}}

