apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-app
    tier: vote
  name: vote-live
spec:
  selector:
    tier: vote
    slot: {{.Values.productionSlot}}
  type: {{.Values.service.type}}
  ports:
  - port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
    nodePort: {{.Values.service.nodePortLive}}





