pipeline{
    agent any
    environment{
        registry="vikasharya000/vote" 
        dockerImage=""  
        dockertoken=credentials("docker-token")
    }
    stages{
        stage('Building our image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry 
                }
            } 
        }
        stage('Deploy our image') { 
            steps { 
                script { 
                    docker.withRegistry( '', "dockerhub-creds" ) { 
                        dockerImage.push("${BUILD_NUMBER}") 
                        dockerImage.push("latest")
                    }
                } 
            }
        }
        stage('Package helm chart and push') {
            steps{
                timeout(time: 10, unit: "SECONDS") {

                    input message: 'approve the helm push?', ok: 'Yes'

                }
                script{
                    sh """
                    minor_version=\$(grep 'version:' ./chart/vote/Chart.yaml | awk -F '.' '{print \$2}')
                    new_minor_version=`expr \$minor_version + 1`
                    cp ./chart/vote/Chart.yaml chart.yaml.tmp && sed "/^\\([[:space:]]*version: \\).*/s//\\10.\${new_minor_version}.0/" < chart.yaml.tmp >./chart/vote/Chart.yaml && rm -f chart.yaml.tmp
                    """

                    sh 'echo \${dockertoken} | helm registry login registry-1.docker.io -u vikasharya000 --password-stdin'
                    sh 'helm package ./chart/vote/'
                    sh 'helm push helm_vote-0.\${new_minor_version}.0.tgz oci://registry-1.docker.io/vikasharya000'
                }
            }
        }
    }
}