pipeline{
    agent any
    environment{
        registry="vikasharya000/vote" 
        dockerImage=""  
    }
    stages{
        stage('Building our image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry 
                }
            } 
        }
        stage('Deploy our image') { 
            steps { 
                script { 
                    docker.withRegistry( '', "dockerhub-creds" ) { 
                        dockerImage.push("${BUILD_NUMBER}") 
                        dockerImage.push("latest")
                    }
                } 
            }
        } 
    }
}