global:
  green:
    enabled: false
  blue:
    enabled: false
  productionSlot: blue

replicas: 1
image: "vikasharya000/vote"
#specify container name using containerName key
containerName: vote
port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31000