productionSlot: green
green:
  image: "vikasharya000/vote"
blue:
  image: "vikasharya000/vote"
replicas: 1
#specify container name using containerName key
containerName: vote
port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePortLive: 31000
  nodePortTest: 31001